language: python
python:
- "2.7"
- "2.6"
- "3.3"
- "3.4"
- "3.5"
install:
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict unittest2; fi
- pip install mock moto responses
- python setup.py install
- pip freeze
script: python -W ignore setup.py test
